# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
stages:
- stage: Build CI
  displayName: 'Provision resources to dev environment'
  jobs:
  - job: Build CI
    displayName: 'dev env provisioning job'

    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'AzureRmPipeline-conn'
        subscriptionId: '75f5dfee-e5f5-4f1a-b126-0b903a8ce713'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'development'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: './azure-main.json'
        overrideParameters: '-devpkApp storedevops -linkedTemplateUri https://raw.githubusercontent.com/mubasharchand/AzureRmPipeline-repo/master/linkedTemplate.json'
        deploymentMode: 'Incremental'
        deploymentName: 'DeployPipelineTemplate'

